base: /
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=5'
languages:
  -
    title: Français
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: fr_CH.UTF-8
    iso-639-1: fr
    navigationTitle: Français
    hreflang: fr-CH
    direction: ''
    flag: fr
  -
    title: Deutsch
    enabled: true
    languageId: 2
    base: /de/
    typo3Language: de
    locale: de_CH.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-CH
    direction: ''
    fallbackType: fallback
    fallbacks: ''
    flag: de
  -
    title: Italiano
    enabled: true
    languageId: 1
    base: /it/
    typo3Language: it
    locale: it_CH.UTF-8
    iso-639-1: it
    navigationTitle: Italiano
    hreflang: it-CH
    direction: ''
    fallbackType: fallback
    fallbacks: ''
    flag: it
rootPageId: 1
websiteTitle: 'Non Nein No'
